### PR TITLE
add error handling to Get

### PR DESCRIPTION
**Pull request by jhjaggars**

### CODE REVIEW

**Comment by iphands** [comment]
I get it... in isolation.
But this should be an impossibly reachable condition at the moment right?

To get to the stage where you can Get all the other check would have had to pass. And a missing or corrupt xrhid would cause a 400 and thus halted execution on the req.

Right?

**Comment by iphands** [comment]
Also dont we kinda want stuff to blow up?
I think the idea behind the middleware is safety such that a request is never ever let through w/o a valid xhrid

**Comment by jhjaggars** [comment]
Hm, it seemed bad to panic the process if you called Get() and the context hadn't been set for some reason, though I guess that's ok actually.  I only ran into it while doing handler testing...

**Comment by iphands** [comment]
I could go either way

**Comment by jhjaggars** [comment]
I'm fine closing this for now.  We can always come back to it if it turns out we need it.

**Pull request closed without merging**
