### PR TITLE
Merge licenses into single file

### PR DESCRIPTION
**Pull request by lzap**
Hey,

documentation does not come up due to misisng license:

https://pkg.go.dev/github.com/redhatinsights/platform-go-middlewares@v0.12.0/logging/cloudwatch

### CODE REVIEW

**Comment by lzap** [comment]
Oh I just noticed there are couple of LICENSE files within some packages. Is it possible to agree on a single license? Looks like pkg.go.dev site require a single LICENSE file in the root directory which is the de-facto standard in FOSS.

**Comment by subpop** [comment]
The `logging` package appears to be code lifted from others and dropped into this project. They're MIT licensed, so we could probably license the whole project as ASL, but keep those LICENSE files in `logging`. We could also consider rewriting the `logging` package to drop the need to carry licenses to other contributors.

**Comment by lzap** [comment]
So I investigated the original roots of the hook code and although the repository does not appear to be "dead" as it is stated in the forking PR, it is definitely old. Tests do not run anymore (this was pre-modules Go code), examples do not compile, it is not in a good shape. Initially I thought I would contributeh MI the changes back but the differences are:

* Upstream now uses AWS session instead AWS config for inicialization (breaking change without v2 btw).
* Our code contains flushing/syncing methods.
* Couple of improvements around synchronization (single goroutine model instead mutiple with mutex).
* Our code never had any tests.
* We have two MIT licenses in the codebase.

My conclusion is: let’s license this repo with MIT, this way there is no legal issues with this, no ASL like I originally proposed. It is so little code that although this is not Red Hat's preferred license, I think it is fine in this case.

Therefore I am moving and merging the LICENSE into the root directory, keeping both authors names and rebasing this PR.

**Comment by subpop** [comment]
LGTM!

**Pull request merged**
